### ISSUE TITLE
Liberty: History action to save previous Start... choices

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-vscode#129]
To avoid having to re-type the same custom parameters each run add a "History" option similar to VS Code for Maven to view past runs

<img width="989" alt="image" src="https://user-images.githubusercontent.com/26146482/186692064-e4191a2e-d107-4827-abd4-e79efce2738b.png">

<img width="878" alt="image" src="https://user-images.githubusercontent.com/26146482/189976999-17385f9a-92c2-4c82-83f6-d370db9a785c.png">

**Comment by kathrynkodama** [comment]
If possible, can we pre-populate the "Start..." command with the last run "Start..." command for that project (most recent in project history)

**Comment by travis1111** [comment]
I assume this is what the current design:

1. Save each `Start...` run (with params)
2. Create a command `Liberty: History...`, once selected, will present a list of previous `Start...` runs with params, and the user select one item from the list, and we will run the selected command/project with saved params.
3. If user select `Start...` on the selected project, we pre-fill the input with the last used params.

If we are going to add a separate action `Liberty: History...`, then we should save all the actions in the history, including `start`, `stop`, `run test` etc, not only the `start...`.

Thus, I am suggesting to change the design.  Here is my suggestion:

1. If user select `Start...` on the selected project, pre-fill the input with the last used params -> this work item.
2. Add a `Liberty: History...` action, it keeps track of all commands, not only `Start...` -> separate work item.

**Comment by travis1111** [comment]
Another option:

Instead of a `new run...` command, when the user clicks on any history entries, we will show the input pre-filled with params, and user can either modify it then run it, or hit run it directly.

This eliminates the `new run...` command, and allows the user to modify any of the params.
