### ISSUE TITLE
Start... command to allow users to edit parameters and build file

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-vscode#144]
~~Edit the "Start..." command behaviour to allow the user to edit the entire "mvn liberty:dev" command.~~

~~As part of this, use the short-form "mvn liberty:dev" command and relative paths to keep the command short.  This applies to the "Start" command as well as "Start..."
From the design:
"Start..." will open an input box with pre-populated `mvn liberty:dev` command that "Start" runs, allowing users to edit the command as needed, e.g. custom parameters, profiles, etc.~~

<img width="277" alt="image" src="https://user-images.githubusercontent.com/26146482/194413061-5fb1e786-3a78-4eca-bb08-c9c8fad2df90.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/26146482/194413197-6d24a71c-2549-4922-b0a3-a4530c042737.png">

**Comment by TrevCraw** [comment]
New design:

- Allow users to modify custom parameters and the targeted build file.
- Pre populate the input box with `-f <<relative-path-to-build-file>>` ie. `-f ear/pom.xml`
- Update the description of the command to "Specify custom parameters for" `mvn liberty:dev` OR `gradle libertyDev` depending on the type of project.
- Set the working directory of the terminal to the selected project.

**Comment by kathrynkodama** [comment]
For Gradle projects, use the `--project-dir=` option when starting dev mode

**Comment by kathrynkodama** [comment]
Latest design based on discussion with the team:
- Do NOT pre-populate the custom Start... with the build file `-f`/`--project-dir` by default.
- Update the description of the command to "Specify custom parameters for" mvn liberty:dev OR gradle libertyDev depending on the type of project.
- Set the working directory of the terminal to the selected project.

@travis1111
