### ISSUE TITLE
Set up Jenkins process for code signing

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#158]
We need to sign the artifacts for this project as part of our build process.
Example for the Liberty Config Language Server can be found here: https://hyc-liberty-tools-team-jenkins.swg-devops.com/job/liberty-language-server-signing/configure

Question: how is this done for Javascript projects?

**Comment by mattbsox** [comment]
You should be able to sign anything with that script. You just need to determine which artifacts need a signature. Anything included in the zip file that is pushed to the signing server will have a .sig file generated.

**Comment by TrevCraw** [comment]
Code signing complete for VSIX artifact:

https://hyc-liberty-tools-team-jenkins.swg-devops.com/job/liberty-tools-vscode-build-code-sign/

The scripts to sign and verify the code is found in the VM
