### ISSUE TITLE
Update build process to pull in LSP4Jakarta

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#159]
Add the LSP4Jakarta step to the Jenkins pipeline so that the LSP4Jakarta jars are part of the `.vsix` artifact.

Once LSP4Jakarta builds are available on the Eclipse repo, we should pull them from there with `gulpfile.js`.

We will also need to update the `gulpfile` to be able to pull from Maven Central for release builds.

**Comment by mattbsox** [comment]
Updated the Jenkins pipeline to clone the LSP4Jakarta repo and build the jars with `npm run buildJakarta`.

**Comment by TrevCraw** [comment]
Complete with https://github.com/OpenLiberty/liberty-tools-vscode/pull/190
