### ISSUE TITLE
Manually adding project to dashboard, wrong project selection is presented

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-vscode#175]
**To reproduce**
Using the getting-started-guide: https://github.com/OpenLiberty/guide-getting-started/tree/prod/finish/src
1. Open VS Code workspace to the root folder of getting-started-guide. The Liberty dashboard automatically detects the start and finish Liberty projects. 
2. Rename the configuration directory to a non-default name in the /finish folder to "src/main/liberty/config2"
3. Remove the Liberty Maven Plugin from the finish/pom.xml
4. finish project is no longer automatically detected by the Liberty dashboard
5. Through the command palette - "Liberty: Add Liberty project", the only option presented in the root getting-started-guide folder, but it should be the finish dir
6. Through the project explorer view, right-click -> "Add as Liberty project", error message that there is no build file detected in the project. 

**Expected behaviour**
Should be able to manually add the finish directory project to the dashboard, through the command palette it should offer you the choice of the pom.xml in the finish dir rather than the root project folder.

**Comment by travis1111** [comment]
I am wondering is this supported?  Isn't the root folder the parent of `src`?

<img width="215" alt="image" src="https://user-images.githubusercontent.com/35569780/200934859-00bbc25c-9c3a-45cf-9558-7d89ce454025.png">

**Comment by kathrynkodama** [comment]
> I am wondering is this supported? Isn't the root folder the parent of `src`?
> 
@travis1111 when trying to manually add the `finish` project it will try to add `guide-getting-started` dir rather than the `finish` dir. Then will say there is no build file found.
