### ISSUE TITLE
Liberty Config Language Server incompatible with XML by Red Hat v0.22.0

### ISSUE THREAD

**Issue by dshimo** [OpenLiberty/liberty-tools-vscode#176]
On the latest version `v0.22.0`:
![image](https://user-images.githubusercontent.com/8934136/200942934-77471930-965d-41fb-b25d-cbaf6a2e611f.png)
Completion, Hover, Diagnostic features are not present
![image](https://user-images.githubusercontent.com/8934136/200943139-3c8a6028-996b-4c3c-9a28-2bbcf7974c76.png)

After downgrading to `v0.21.0`:
![image](https://user-images.githubusercontent.com/8934136/200942804-bab1103a-6daf-4b2c-a83a-b08a6c4e0ac9.png)
Completion, Hover, Diagnostic features return
![image](https://user-images.githubusercontent.com/8934136/200942721-47e5f154-48c3-4583-8407-2e50e9b16c94.png)

**Comment by evie-lau** [comment]
In my environment, I have XML by Red Hat 0.22.0, and Liberty LemminX still works for me.

![image](https://user-images.githubusercontent.com/689163/200943956-37fef9cb-5037-4979-811a-7ff7fffd3e4b.png)

**Comment by dshimo** [comment]
Pasting a similar image for comparison
![image](https://user-images.githubusercontent.com/8934136/200944303-30837678-d4c2-4dd2-9f33-df706182777f.png)

**Comment by travis1111** [comment]
It works for me (Mac, 0.22 xml)

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/35569780/202244765-562175e3-70be-4db7-8025-602a10a463fc.png">

**Comment by dshimo** [comment]
I discovered that the error was a failed auto detect language mode, where VSCode assigned the `server.xml` file to PHP.
The errors did not bubble to my client because I developed with a remote system.

**Comment by dshimo** [comment]
![Language Mode](https://user-images.githubusercontent.com/8934136/202287454-5012160e-c354-4c88-90ed-f3d1f25999dd.png)

![image](https://user-images.githubusercontent.com/8934136/202287416-42c1caeb-18ac-48db-97cd-d11779eca91d.png)

**Comment by kathrynkodama** [comment]
@dshimo do we have any control over which file type is assigned? Can we programatically ensure the server.xml is set to XML by default?
