### ISSUE TITLE
Document how to troubleshoot/configure Java for language servers

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-vscode#178]
Document how to configure JDT LS Java Home that the langauge servers use, see: 
https://github.com/redhat-developer/vscode-java#java-tooling-jdk

<img width="1202" alt="image (14)" src="https://user-images.githubusercontent.com/26146482/201194918-81f227bb-0036-4c3f-bc07-8933557f630d.png">

**Comment by dshimo** [comment]
Addressed with #268
