### ISSUE TITLE
does not suggest tag with `<>`  brackets 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/liberty-tools-vscode#185]
in the server.xml, proposals do not generate `<...>` 

- <img width="510" alt="Screen Shot 2022-11-21 at 5 15 00 PM" src="https://user-images.githubusercontent.com/29576299/203411196-9f0d7522-7502-48f4-975d-bc9f39194fb4.png">

    - expected `<webApplication></webApplication>`

and the icon "abc" looks strange. 

- <img width="305" alt="Screen Shot 2022-11-21 at 5 11 10 PM" src="https://user-images.githubusercontent.com/29576299/203411261-1dc870be-7acb-427f-9fe4-5d11bc603e22.png">

**Comment by dshimo** [comment]
This has surfaced that the code to use the same JRE amongst our language servers doesn't influence how LemminX starts. The bug that slips through comes from having a Java17 RedHat JRE while using Java11 with `JAVA_HOME`. The language servers use Java17 as intended, but LemminX will default to a different runtime and `*.xml` functionality drops.

For now, the PR will add a more strict check, verifying both runtime versions.

To resolve this, a user can 
1) set their default Java runtime to 17; 
2) define `xml.java.home` to point to a Java17 runtime for LemminX, similar to how `java.jdt.ls.java.home` gets used for lang servers; 
3) Try to automate in a later enhancement.

**Comment by dshimo** [comment]
Not resolved automatically, but VS Code now reveals a message that LCLS may not have activated in a given environment.

![image](https://user-images.githubusercontent.com/8934136/206286680-1d40a477-3a0a-4c8e-acc9-ede270dded1c.png)
