### ISSUE TITLE
Completion suggestions are sometimes missing

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#194]
Every so often, VS Code seems to take over the completion suggestions and does not provide any of the suggestions that Liberty Tools would be offering from the language servers. Even when hitting "ctrl + space", VS Code just provides its basic "you've typed this before" suggestion. So far, have only seen this in server.xml. To reproduce the issue in the image, you must type "mes" and then hit "ctrl + space"

![completion-bug](https://user-images.githubusercontent.com/5885743/205523907-4c264d32-b031-46d7-8bba-72b097a41e86.png)

**Comment by TrevCraw** [comment]
The issue reported by @irobins is a separate bug from the one reported in this issue.
@cherylking discovered that it was caused by the "XML Language Support by Red Hat" extension updating to a later version of Eclipse LemMinX (0.25.0) which contains a breaking change.

If using the current Liberty Tools for VS Code (0.1.12), below is the workaround shared by @cherylking.

1. Go the the Extensions tab.
2. Find the "XML Language Support by Red Hat" extension in your list of installed extensions.
3. Right click and select "Install Another Version..."
4. Then pick the 0.24.0 version from 3 months ago.
5. Install that and select "Reload required" button.

Building the extension from the main branch will also resolve this issue.

**Comment by TrevCraw** [comment]
This issue was reported by SVT earlier this week and there are some more details there: https://github.com/OpenLiberty/liberty-tools-vscode/issues/248

**Comment by TrevCraw** [comment]
Unable to reproduce using LT for VS Code 23.0.6 release and latest VS Code version 1.81.1

**Comment by irobins** [comment]
Ah I figured out my issue. I had a back-level version of the XML Language Support extension (0.24.0), which I had previously downgraded to and forgot to replace with the latest version (0.26.1) when moving to Liberty tools (23.0.6).
So my issue was user error. 
^ @cherylking

**Comment by TrevCraw** [comment]
@vaisakhkannan Can you investigate to see if it is possible to turn off "Show Words" from our extension? Or if it is possible to turn it off for specific files? If we were to somehow disable it from our extension, we would only want to turn it off for certain files (ie. server.xml). My guess is VS Code would not provide this ability to extensions, but it is worth looking into.

**Comment by TrevCraw** [comment]
Resolution for this issue has been documented on the Common Issues wiki page: https://github.com/OpenLiberty/liberty-tools-vscode/wiki/Common-Issues
