### ISSUE TITLE
Add explanation/instructions to empty dashboard

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-vscode#203]
See https://github.com/OpenLiberty/liberty-tools-eclipse/issues/294

**Comment by gasgithub** [comment]
One additional reason to shown in the link above might be too old VS Code version or missing Java 17. 
I had this case, although tools have been successfully installed the Liberty dashboard was empty, and there was no support for server.xml.

**Comment by TrevCraw** [comment]
Based on discussions with @Rahul-Biju and @turkeylurkey , below is what we propose should be displayed in the Liberty Dashboard when no projects are available:

- While the Liberty Dashboard is loading:
  `Liberty Dashboard loading…`
- After the Liberty Dashboard has loaded:
  ```
  - If no projects are open in the VS Code Explorer, open or create a Liberty project using the File menu.
  - If there is one or more existing Maven or Gradle projects open in the VS Code Explorer, try one of the following:
    - Configure the Liberty build plugin in the build file of an existing Maven or Gradle project.
    - Add a server.xml file to an existing Maven or Gradle project at “src/main/liberty/config”.
    - Manually add an existing Maven or Gradle project to the Liberty Dashboard through the VS Code command palette action “Liberty: Add project to Liberty Dashboard”.
    ```

**Comment by TrevCraw** [comment]
@scottkurz since you initially opened https://github.com/OpenLiberty/liberty-tools-eclipse/issues/294, do you have any thoughts on what the team is suggesting we display for an empty dashboard?

**Comment by TrevCraw** [comment]
@gasgithub thank you for your suggestions. The latest version of Liberty Tools for VS Code (23.0.9) requires VS Code version 1.78.0 or newer. I believe that an older version of VS Code would prevent the Liberty Tools extension from being installed. 

As for missing Java 17, we should have improved our error messaging for that scenario in 23.0.9 - you can find the documentation for that here: https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/docs/user-guide.md#configure-your-java-runtime-for-language-servers

If you still have questions or still have problems loading your projects with Liberty Tools version 23.0.9, please let us know and we would be happy to help.
