### ISSUE TITLE
test for Debug action in dev mode capabilities automation

### ISSUE THREAD

**Issue by vkavitha** [OpenLiberty/liberty-tools-vscode#230]

**Comment by ragudiko** [comment]
Analysis of getting debugging options while running extension test.
There are multiple options to run test in debug mode. Below are 3 options mentioned [here](https://code.visualstudio.com/docs/nodejs/nodejs-debugging)(VSCode documentation).
[Stackoverflow discussion thread](https://stackoverflow.com/questions/34835082/how-to-debug-using-npm-run-scripts-from-vscode)

1) One easiest way to debug test case is to run npm run test using "Javascript Debug Terminal". There are other options(config changes in package.json and launch.json) which I will evaluate.
![image](https://user-images.githubusercontent.com/28623113/221171383-44955592-7f87-4447-a947-a4a7819bfd66.png)

2) Within VScode-- [Toggle Auto Attach](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_auto-attach) command from the Command Palette (⇧⌘P)
chose Auto Attach: Always
After enabling Auto Attach, you'll need to restart your terminal. This can be done by clicking the :warning: icon in the top right of the terminal, or just creating a new one. Then, the debugger should attach to your program within a second:
in my case only - Auto Attach: Always works
Note: This works with Integrated Terminal, no need to switch to JavaScript Debug Terminal. I used zsh terminal.

3) via [configuration changes](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools)
package.json
"debug": "npm run test-compile && extest setup-and-run out/test/*.js",
launch.json
{
            "name": "Launch Debugger via npm",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run-script", "debug"]
          }
The above configuration creates "Launch Debugger via npm" similar to Run Extension/Extension Tests options

**Comment by ragudiko** [comment]
All 3 options feasible and easy to use for debugging. 
For dev mode-->liberty dashboard-->project--> attach debugger, I need to analyze which options will be relevant.
I will have to look remote debugging/other options before moving to dev mode.

**Comment by ragudiko** [comment]
Moving to next milestone
Attach debugger is done, but there are few challenges while detaching debug session/stopping the server.

**Comment by ragudiko** [comment]
test case done
https://github.com/OpenLiberty/liberty-tools-vscode/commit/983b77b52fbb4da485cdf19b2fa2e6f19ba6ab03
