### ISSUE TITLE
Start in container option not appearing if parent folder of Liberty project is opened in VS Code

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#258]
Using the [getting started guide](https://github.com/openliberty/guide-getting-started), which contains a Dockerfile in the `start` and `finish` directories.

If you open the Liberty project directly (ie. the `finish` dir), you will see the "Start in container" option:
![container-2](https://github.com/OpenLiberty/liberty-tools-vscode/assets/5885743/321cea69-0014-44f5-a1c4-3110447ba639)

If you open the project in VS Code by selecting a parent folder to the Liberty project(s), in this case "getting-started-guide" which contains `start` and `finish` Liberty projects, then the option to "Start in container" is not available:
![container-1](https://github.com/OpenLiberty/liberty-tools-vscode/assets/5885743/00b286e9-64fd-4715-93df-cd07ecce4c10)

The "Start in container" option should be available regardless of which folder is opened in VS Code.

**Comment by cherylking** [comment]
This does not seem like a common scenario except for our guides. If the menu option were available on the parent folder, which module would it actually start in container mode? The `start` or the `finish`? How would it decide? Maybe I am overthinking this.

**Comment by TrevCraw** [comment]
documented here: https://github.com/OpenLiberty/liberty-tools-vscode/wiki/Known-Problems-and-Limitations
