### ISSUE TITLE
maven wrapper not working in Windows.

### ISSUE THREAD

**Issue by ajm01** [OpenLiberty/liberty-tools-vscode#260]
maven wrapper not working in Windows.

Steps to recreate

1. Install latest LT VScode driver
2. Install a maven / Java17 application
3. click on start from the Liberty Dashboard

result:
![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/31104727/a4f82b2d-3cf3-4e97-a5bc-172efa4879db)

also happens when using the command palette as well

**Comment by ajm01** [comment]
VSCode is defaulted to use bash shell and on Windows this will cause the -f arg to the start command to be interpreted incorrectly.

To revert to the Windows PowerShell in terminal i removed the setting string: (from settings.json)
`"terminal.integrated.shell.windows": "[path to bash shell]"`

This allowed powershell to run the dashboard commands which were then successful

**Comment by TrevCraw** [comment]
documented here: https://github.com/OpenLiberty/liberty-tools-vscode/wiki/Common-Issues
