### ISSUE TITLE
Dependent extensions of liberty tools are not installing automatically in linux, when installing through vsix file.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-vscode#290]
OS - redhat 9.2
vscode version - 1.82

After installing liberty-tools-vscode through vsix file(v23.0.9), the following dependent extensions are not installing automatically.

- Language Support for Java
- XML
- Tools for MicroProfile

![Screenshot 2023-09-15 at 12 21 55 PM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/114654953/5376bfa2-a7dd-4d3e-bf61-74ea76454e95)

**Comment by dshimo** [comment]
I did not encounter this issue while installing the 23.0.9-SNAPSHOT .vsix in my VS Code.

VS Code Version: 1.82.1
OS: Linux x64 6.5.2-arch1-1

**Comment by aparnamichael** [comment]
Tested in  redhat 9.2 and ubuntu 18.
vscode: 1.82 

Extensions are installed automatically. 
Came to a conclusion that the issue faced was due to fire machine connectivity issue.
