### ISSUE TITLE
Integrate newest LSP4Jakarta release when available

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#295]
The upcoming release for LSP4Jakarta may require code changes to integrate the language server with the language client. The `bindRequests` in [src/extension.ts](https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/src/extension.ts#L79-L82) may need to be updated, as well as other potential changes.

When the newest release of LSP4Jakarta becomes available, update all references to latest version in preparation for next release.

There are two dependencies that need updating:
- org.eclipse.lsp4jakarta.ls-0.1.1-jar-with-dependencies.jar
- org.eclipse.lsp4jakarta.jdt.core-0.1.1.jar

These three files are affected:
- gulpfile.js (make sure to update https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/gulpfile.js#L89-L90)
- package.json
- src/extension.ts

Test to confirm no regression is introduced.

**Comment by ajm01** [comment]
for your awareness - the new jakarta LS messages are now as follows:
