### ISSUE TITLE
SVT: Repeated smarter planet log message in VSCode terminal when starting application

### ISSUE THREAD

**Issue by hanczaryk** [OpenLiberty/liberty-tools-vscode#302]
SVT: Repeated smarter planet log message in VSCode terminal when starting application

On my Windows 11 laptop, I've installed VSCode 1.83.1 with the 10/21 liberty-dev-vscode-ext-23.0.12-SNAPSHOT.vsix extension from box folder installed.

I installed maven 3.9.5 on my laptop. Under the Liberty Dashboard, I right clicked my application, MPProShop, and clicked 'Start' or 'Start in container' and was able to successfully observe the server started.

In reading through the VSCode terminal logged messages, I found the following two concurrent messages mentioning 'smarter planet'.

```
[INFO] [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 49.860 seconds. 
[INFO] CWWKM2015I: Match number: 1 is [10/23/23, 10:49:26:550 EDT] 0000003f com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 49.860 seconds..
```

I'm not sure why the 2nd message displays 'Match number: 1 is' would be displayed to the user.

This is very minor but seemed odd from a serviceability perspective on why the message was printed out twice.

**Comment by hanczaryk** [comment]
FYI, I just encountered the same repeated message when testing Liberty Tools on IntelliJ, so this doesn't appear to be specific to VSCode.

**Comment by cherylking** [comment]
I'm 99% sure that message is coming from Liberty itself. The Liberty Maven plugin is just logging to the console what is in messages.log.

**Comment by cherylking** [comment]
Closing as working as designed.

**Comment by cherylking** [comment]
One message is from Liberty itself. The other is from our plugin verifying it found the message it was looking for. Sometimes that will say it found no match, or more than one match.

**Comment by scottkurz** [comment]
To second Cheryl's point.. if you run with:  `<logging .. consoleLogLevel="OFF"/>` you won't see the one from the Liberty runtime.  They're separate layers smashed into one output stream.   Yes this is a bit of duplication in this one case but it seems the approach has been OK overall .

**Comment by hanczaryk** [comment]
I think this was a very minor issue, so if we can set consoleLogLevel to OFF, then I'd personally be fine with it.  I'll try with this later today.
