### ISSUE TITLE
Diagnostic Found in <basicRegistry> of server.xml after Dev Start Action

### ISSUE THREAD

**Issue by Rahul-Biju** [OpenLiberty/liberty-tools-vscode#308]
When testing the open-liberty.liberty-dev-vscode-ext-23.0.12-SNAPSHOT release driver, I encountered the following diagnostics after Start action . This issue was observed on Gradle project running on Windows machine.

Vscode version : 1.83.1

<img width="1019" alt="Screenshot 2023-11-02 at 9 22 10 PM" src="https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/8b74752d-1d9b-43dd-94a8-c229ec8fe0d2">

Sometimes, after completing the 'dev start' action, the diagnostic may disappear.

**Comment by vaisakhkannan** [comment]
I have been able to reproduce the issue related to this problem after the Dev start action. I am uploading the screen recordings when I encountered these issues.

https://github.com/OpenLiberty/liberty-tools-vscode/assets/133869023/1db7527e-b2b7-4baf-aa2f-99e09ac92132

 To specify the issues, I found diagnostics on the dev start action in the following config elements of server.xml

<server>
 <basicRegistry>
<httpEndpoint>
<applicationManager>
<webApplication>
<ssl>

I found these issues in both Gradle and Maven projects on Mac and Linux machines as well.
Here are the steps to reproduce the issue:

1. Open a Gradle/Maven project.
2. Execute "gradle clean" or "mvn clean."
3. Start the development action.

During the **start action** process, we can see diagnostics, but I noticed that the diagnostics disappear after the **start action** is completed.
If we do **stop action** and then perform the **start action** again , from the second time onwards, no diagnostics are visible on config elements of server.xml
Recently, I discovered that the issue immediately arises after performing "gradle clean" or "mvn clean" on the project.

**Comment by anusreelakshmi934** [comment]
I faced the same issue on my Mac while using both Maven and Gradle files. This error only seems to occur during the initial startup of the development action. Once the development mode is up and running, the error disappears.

**Comment by cherylking** [comment]
It would be helpful to include the actual diagnostic messages, but I believe these might be expected. I need to know the following:

1) What features are listed in the xml file in question.
2) What Liberty runtime/version are you installing as part of the start action (look in pom.xml/build.gradle).
3) What diagnostic messages are you seeing (hover of the diagnostic and provide the text along with any quick fixes provided)?

Also, do you have a recent driver installed for Liberty Tools? We made two or three fixes this week. One involved using the default cached feature list in certain scenarios, which could affect this behavior.

**Comment by cherylking** [comment]
To explain how the config element validation works:

1) On a clean project, it uses the default cached feature list. Probably won't see much red since we used `openliberty-runtime` for this which includes all features for OL.
2) When you run the start action, Liberty gets installed. 
3) LCLS will then generate a feature list from the installed Liberty. If it is a `openliberty-kernel` runtime (which is the default), it will have virtually no features installed and you will see a lot of red config elements.
4) Then features get installed based on what is in the server.xml (and possibly other config files, including the build file).
5) LCLS will regenerate the feature list to pick up the newly installed feature(s).
6) Only red lines should appear for config elements that do not have a feature configured in that xml file.

**Comment by Rahul-Biju** [comment]
Here is the update :

1. What features are listed in the xml file in question.

![Screenshot 2023-11-07 at 12 00 46 PM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/69234174-8e29-4605-bcc5-1597ce5ecdfb)

2. What Liberty runtime/version are you installing as part of the start action (look in pom.xml/build.gradle).
               
      liberty-maven-plugin : 3.9
      liberty-gradle-plugin : 3.7
                   
3. What diagnostic messages are you seeing (hover of the diagnostic and provide the text along with any quick fixes provided)?

While hovering <basicRegistry> the below mentioned diagnostics and quick fix has been shown:

![Screenshot 2023-11-07 at 11 58 00 AM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/7ab4973b-4299-4224-a281-857710fab668)


![Screenshot 2023-11-07 at 11 58 13 AM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/8d6d8dbb-e05f-4f5f-baa6-b5d245ac882e)

While hovering all other tags with error in sever.xml the below mentioned diagnostics and quick fix has been shown:

![Screenshot 2023-11-07 at 12 03 21 PM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/4061f8cf-7237-42e8-aa17-5b5a8b5dfa17)

![Screenshot 2023-11-07 at 12 03 33 PM](https://github.com/OpenLiberty/liberty-tools-vscode/assets/133862121/a190e48e-a43d-413e-98cb-10c99a5ecee2)

Note : We have installed recent driver for the Liberty Tools.

**Comment by cherylking** [comment]
> What Liberty runtime/version are you installing as part of the start action (look in pom.xml/build.gradle).

> liberty-maven-plugin : 3.9
> liberty-gradle-plugin : 3.7

@Rahul-Biju Those are the plugin versions, not the version of Liberty runtime. I want the artifactId and version for Liberty that was specified in the build file. If none was specified in the plugin configuration, then let me know that. In that case, the default is the latest version of `liberty-kernel` which has virtually no features installed and leads to behavior like you are seeing.

**Comment by Rahul-Biju** [comment]
@cherylking 
 We are not specifying the Liberty explicitly in build file. Could you please let us know the configuration for the same.

**Comment by cherylking** [comment]
@Rahul-Biju To specify a version of the Liberty runtime, you just need to add this to the plugin config:

```
<configuration>
        <runtimeArtifact>
            <groupId>com.ibm.websphere.appserver.runtime</groupId>
            <artifactId>wlp-webProfile8</artifactId>
            <version>23.0.0.9</version>
        </runtimeArtifact>
    </configuration>
```

groupid should be `io.openliberty` for OL. You can find a list of artifacts in Maven Central for each of those groupId, or reference our [doc](https://github.com/OpenLiberty/ci.maven/blob/main/docs/installation-configuration.md#using-a-maven-artifact) (which can be slightly out of date).

**Comment by Rahul-Biju** [comment]
@cherylking 
me and @vaisakhkannan , we both checked this issue on both maven and Gradle , when we add openliberty-runtime instead of the default openliberty-kernel, we won't get diagnostics on server startup that we see in the openliberty-kernel.
We saw the diagnostic on the server element only once during setup of openliberty-runtime. After that we are not getting any diagnostics.
