### ISSUE TITLE
Completion does not replace text typed by user in boostrap.properties

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#332]
Refer to https://github.com/OpenLiberty/liberty-language-server/issues/276

There may be work required on the VS Code client side.

**Comment by JoshwinThomasIBM** [comment]
Tested the above case with LCLS 2.2 snapshot , the above issue is resolved . see the screen recording attached 


https://github.com/user-attachments/assets/9c90572d-e9e8-4653-8ee7-ea87c00398d4



We get suggestions even if we input first few characters and then some characters that comes in between the keys .However if we select one from the suggestions and then undo and then  try for suggestions we don't get any. see the screen recording from 00:40

**Comment by TrevCraw** [comment]
Thank you for reviewing this issue @JoshwinThomasIBM. If when typing forward, suggestions are displayed for something like `com.ibm.logg`, then suggestions should also be displayed after deleting to get back to the same point. From a user experience standpoint, I would not expect the suggestions to depend on adding or removing characters. Please open a new issue in https://github.com/OpenLiberty/liberty-language-server and investigate to see if this problem occurs in IntelliJ and Eclipse as well.

**Comment by JoshwinThomasIBM** [comment]
Hi @TrevCraw , raised the [issue](https://github.com/OpenLiberty/liberty-language-server/issues/314) and please see the comments from them [here](https://github.com/OpenLiberty/liberty-language-server/issues/314#issuecomment-2429165094) ,

**Comment by JoshwinThomasIBM** [comment]
Tested the issue "Completion does not replace text typed by user in boostrap.properties" with the latest LCLS 2.2 SNAPSHOT and the issue is fixed
