### ISSUE TITLE
Test reports can be in a new location

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#340]
Refer to https://github.com/OpenLiberty/liberty-tools-intellij/issues/934 from LTI.

With the recent updates to version `3.5.0` for the Maven Surefire Plugin and Maven Failsafe Plugin, test reports are created in a new location by default.

We need to update the code where we currently hardcode the old location: https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/src/liberty/devCommands.ts#L493

The current proposal is to check both new and old report locations, starting with the new location first.

**Comment by JoshwinThomasIBM** [comment]
Code changes are completed and is for review , PR https://github.com/OpenLiberty/liberty-tools-vscode/pull/347

**Comment by JoshwinThomasIBM** [comment]
Now we have hardcoded the directories to check for the reports. With the upcoming surefire report plugin releases , if is any change with the directories then we can add the directories to look for as a list or as a property and iterate over each of them to check the availability of the report
