### ISSUE TITLE
Diagnostics are not displayed for invalid values, if there is an empty line before the variable.

### ISSUE THREAD

**Issue by aparnamichael** [OpenLiberty/liberty-tools-vscode#343]
Steps to reproduce:

1. Add a variable "WLP_LOGGING_CONSOLE_FORMAT=DEV".
2. Add an empty line (\n)
3. Add another variable and assign an invalid value. "WLP_LOGGING_CONSOLE_LOGLEVEL=NONE"
4. The diagnostic is not showing for the invalid value - "NONE"

https://github.com/user-attachments/assets/8332af7c-49f7-4af4-8bdc-9c72e213a5ed

**Comment by JoshwinThomasIBM** [comment]
When we add the same key and value  multiple times (where the value is an invalid one ) then the diagnostic only appears for the last entry , please see the below screenshot 

<img width="742" alt="image" src="https://github.com/user-attachments/assets/b2eb5dcb-9fc6-43d0-8e4a-0581393c0615">

not sure if this is a valid case , in prod we might not have multiple entry for the same key . just adding as an observation

**Comment by arunvenmany-ibm** [comment]
I think this can be ignored. For duplicate key in VSCode, only last entry is considered, hence there is diagnostic to be showing on the last entry for duplicate keys
