### ISSUE TITLE
Integrate new LSP4Jakarta release when available

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-vscode#361]
When the newest release of LSP4Jakarta becomes available, update all references to latest version in preparation for next release.

There are two dependencies that need updating:
- org.eclipse.lsp4jakarta.ls-x.y.z-jar-with-dependencies.jar
- org.eclipse.lsp4jakarta.jdt.core-x.y.z.jar

These three files are affected:
- gulpfile.js
- package.json
- src/extension.ts

Complete the following:
- [x] Update to snapshot version
- [x] Test to confirm no regression is introduced.
- [x] Update to release version when available
- Verify the following fixes:
  - [x] https://github.com/OpenLiberty/liberty-tools-vscode/issues/336
  - [x] https://github.com/OpenLiberty/liberty-tools-vscode/issues/207
  - [x] https://github.com/OpenLiberty/liberty-tools-vscode/issues/362

**Comment by aparnamichael** [comment]
Tested with 0.2.2-Snapshot and all the Jakarta features are working as expected.
