### ISSUE TITLE
Add a way to quickly tell maven and gradle projects apart.

### ISSUE THREAD

**Issue by rzgry** [OpenLiberty/liberty-tools-vscode#44]
Currently it is very difficult to tell maven and gradle projects with the same name apart.  Ex. People trying out devmode using the demo-devmode project. https://github.com/OpenLiberty/demo-devmode

![image](https://user-images.githubusercontent.com/16768710/73205439-00165580-410f-11ea-9f74-c1e709299aae.png)

Would be nice to have a way to quickly tell which type of project you are running dev-mode for.

One option could be adding the maven / gradle logo in the corner of the icon.

**Comment by ericglau** [comment]
https://github.com/OpenLiberty/demo-devmode/issues/26 will change the project names to indicate maven or gradle in the sample project.  

It will still be useful to improve this though.  Another option is to use separate sections (e.g. `Liberty Dev Dashboard - Maven` and `Liberty Dev Dashboard - Gradle`).

**Comment by bensonnw** [comment]
![image](https://user-images.githubusercontent.com/58234271/75790886-cc47d480-5d39-11ea-8a53-be25242e9e62.png)
Can we ask for the icons from design team?

**Comment by yeekangc** [comment]
This is not simply Maven vs Gradle alone but in general if we see projects of the same name but from different locations too.

**Comment by kathrynkodama** [comment]
Closed since we have the new icons for Maven and Gradle projects
