### ISSUE TITLE
Consume the Liberty Language Server and Liberty LemMinx LS ext

### ISSUE THREAD

**Issue by rzgry** [OpenLiberty/liberty-tools-vscode#63]
Completion
- [ ] server.xml schema elements
- [ ] Open Liberty features

Diagnostics
- [ ] Unknown/invalid server.xml elements
- [ ] Duplicate features
- [ ] Unknown features

Hover
- [ ] Hover documentation of server.xml schema elements
- [ ] Hover documentation for liberty server features

Other
- [ ] Handle version of liberty

**Comment by yeekangc** [comment]
Looks fine to me as a MVP for checking and assisting with an existing config.

**Comment by angelozerr** [comment]
Other idea:

 * variable completion, definition and validation:

Given this XML file:

```xml
<server description="Sample Liberty server">

    <variable name="default.http.port" defaultValue="9080"/>
    <httpEndpoint host="*" httpPort="${default.http.port}"
</server>
```

Completion on  | `<httpEndpoint host="*" httpPort="|` should show `${default.http.port}`

 * featureManager:

```xml
<featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>jsonp-1.1</feature>
        <feature>cdi-2.0</feature>
        <feature>mpMetrics-2.3</feature>
        <feature>mpHealth-2.2</feature>
        <feature>mpConfig-1.4</feature>
    </featureManager>
```

Completion on feature text node should show jaxrs-2.1, etc (don't know how to get this list, perhaps this list is computed from a Java classpath?)

**Comment by kathrynkodama** [comment]
Completed, implementation is on https://github.com/OpenLiberty/liberty-tools-vscode/tree/liberty-ls-prototype branch
